apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: progapview-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/server-alias: progap.policiacivil.go.gov.br
spec:
  tls:
    - hosts:
        - progap-homo.policiacivil.go.gov.br
        - progap.policiacivil.go.gov.br
      secretName: certificado-pc
  rules:
    - host: progap-homo.policiacivil.go.gov.br
      http:
        paths:
          - path: /
            backend:
              serviceName: progapview-service
              servicePort: 80
